services:
  db:
    image: postgres:16
    container_name: ipms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ipms
      POSTGRES_USER: ipms
      POSTGRES_PASSWORD: ipmspassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  upload:
    build:
      context: ./microservices/upload
    container_name: ipms-upload
    restart: unless-stopped
    environment:
      PORT: 4000
      UPLOAD_DIR: /data/uploads
      PUBLIC_BASE_URL: http://localhost:4000
    ports:
      - "4000:4000"
    volumes:
      - upload_data:/data/uploads

volumes:
  postgres_data:
  upload_data:
